export const SliderData = [
    {
      image:
        require("./../../data/image/image23.jpg")
    },
    {
      image:
        require("./../../data/image/image15.jpg")
    },
    {
      image:
        require("./../../data/image/image34.jpg")
    },
    {
      image:
        require("./../../data/image/image39.jpg")
    },
    {
      image:
        require("./../../data/image/image10.jpg")
    }
  ];

  export const SliderData1 = [
    {
      image:
        require("./../../data/image/image7.jpg")
    },
    {
      image:
        require("./../../data/image/image8.jpg")
    },
    {
      image:
        require("./../../data/image/image37.jpg")
    },
    {
      image:
        require("./../../data/image/image40.jpg")
    },
    {
      image:
        require("./../../data/image/image33.jpg")
    }
  ];